spring:
  application:
    name: audit-service

  # Exclude JaVers auto-configuration to use manual configuration
  autoconfigure:
    exclude:
      - org.javers.spring.boot.sql.JaversSqlAutoConfiguration

# HSQLDB Configuration
  datasource:
    url: jdbc:hsqldb:mem:auditdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password:

# Spring SQL initialization
  sql:
    init:
      mode: always
  init:
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql

# JPA / Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Server Configuration
server:
  port: 8080
